type Query {
  # Message query
  message(id: ID): [Message!]!
  messages: [Message!]!
  # Query to get all users or a single user using id 
  users: [User!]!
  user(id: ID!): User
  # Query to display all posts or paginated posts or a single post using id
  posts: [Post!]!
  paginatedPosts(page: Int!, limit: Int!, sortBy: String, order: String): PaginatedPosts!
  post(id: ID!): Post
  # Query to display all comments or a single comment using id
  comments: [Comment!]!
  comment(id: ID!): Comment
  ChatUsers:[ChatUser!]!
  ChatMessages:[ChatMessage!]!
  allMessages: [ChatUser]!
}

type Mutation {
  postMessage(content: String!, authorID: ID!, title:String!): Message!
  updateUser(id: ID!, name: String, email: String): User
  deleteComment(id: ID!): Boolean
  createPost(title: String!, content: String!, authorID: ID!): Post
  createComment(content: String!, authorID: String!, postID: String!): Comment!
  registerUser(name: String!, email: String!,password: String!): User!
  loginUser(email: String!, password: String!): User!

  register(username:String!,password:String!):ChatUser!
  login(username:String!,password:String!):AuthPayload!
  sendMessage(content:String!):ChatMessage!
  logout:LogoutResponse!


}

type Subscription {
  messageAdded: Message!
  commentAdded: Comment!
  userAdded: User!
  userLogged: String!
  userStatusChanged: ChatUser!
}